### ISSUE TITLE
A disclaimer and copyright for ECDE pages

### ISSUE THREAD

**Issue by martinjuckes** [cedadev/c3s_434_ecde_page_text#21]
ClimateADAPT pages have a [disclaimer ](https://www.eea.europa.eu/legal/disclaimer) which starts "The European Environment Agency (EEA) maintains this site to enhance public access to information about its activities. Our goal is ......" and goes on to say that the information on the site " ... does not necessarily reflect the official opinion of the EEA and other European Union institutions and bodies."

The Climate Data Store has a [similar disclaimer](https://cds.climate.copernicus.eu/disclaimer-privacy) , starting "ECMWF maintains this website to enhance public access to information about the European Union’s Copernicus Programme" and including "ECMWF cannot warrant that any information provided by the Copernicus Climate Change Service will be entirely free from errors or omissions or that such errors or omissions can or will be rectified entirely".

CDS dataset pages all have a license text which can vary from page to page, but there is a standard form for (apparently) all SIS products. This is accessible as a pop-up from the "Licence to use Copernicus Products" link on dataset pages such as [this one](https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-health-vector?tab=overview). The text can be exported as a PDF, copied to this repo [here](https://github.com/cedadev/c3s_434_ecde_page_text/blob/main/licence-to-use-copernicus-products.pdf).

The ECDE products are, according to the terms of the C3S 434 contract, the property of C3S and the EU, like any other SIS product available from the CDS, so the Copernicus Product license should apply.

Can we provide this license text via a link labelled, for example, "License conditions for ECDE content"?

Should we provide a brief staging page, such as the "[Privacy and Legal Notices](https://climate-adapt.eea.europa.eu/privacy-and-legal-notice)" page used in Climate-ADAPT, and link to the license from there?

**Comment by silviadallacosta** [comment]
we propose 
1) to add a footnote/Disclaimer  in the landing page of the data explorer, e.g.
"Please note that the European Climate Data Explorer  is externally managed and maintained by the ECMWF, for any technical issues or questions about the data behind please contact ECMWF email (if possible). ECMWF maintains this website to enhance public access to information about the European Union’s Copernicus Programme but  cannot warrant that any information provided by the Copernicus Climate Change Service will be entirely free from errors or omissions or that such errors or omissions can or will be rectified entirely".
To give Attribution refer to "Copernicus Licence agreement (PDF link: https://cds.climate.copernicus.eu/api/v2/terms/static/licence-to-use-copernicus-products.pdf) Article 5.

2) Add to each data/indicator page  a footnote (hardcoded), according to art. 5.1.1 of the above PDF stating:
• 'Generated using Copernicus Climate Change Service information [Year]' and/or
• 'Generated using Copernicus Atmosphere Monitoring Service information [Year]'.
if we add the year this has to be automatically  updated, otherwise we simplify the note by removing the year.
Optionally we can link the PDF also here

**Comment by martinjuckes** [comment]
There should also be a list of supported browsers in (or near) the disclaimer:

Min tested browsers: Chrome 60, Firefox 52, Safari 10.1, Edge 15.

Internet Explorer is not supported by the CDS Toolbox.

**Comment by charliepascoe** [comment]
Closing but logging the need for a list of supported browsers in #59
